// import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/tanstackProvider";
import { Providers } from "./providerNextUi";
import Header from "./header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <TanstackProvider>
        <html lang="en">
          <body>
              <Providers>
                <Header/>
                {children}
              </Providers>
              <script type="module" src="https://unpkg.com/@splinetool/viewer@1.0.93/build/spline-viewer.js"></script>
          </body>
        </html>
    </TanstackProvider>
  );
}
